#!/usr/bin/env bash
#Transer a file from our cleint to a server

#Check if a number of arguments is less then 4
if [ $# -lt 4 ]; then
echo "Usage: 0-transer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"
fi
