#!/usr/bin/env bash

#Updating the package list
echo "Updating package list..."
sudo apt-get update -y

#Now we are going to install something called Nginx
echo "Installing Nginx..."
sudo apt-get install nginx -y

#Lets turn on Nginx
echo "Starting Nginx..."
sudo service nginx start

#Now we are going to make a special web page that says Hello World
echo "Creating a Hello World page..."
echo "Hello World!" | sudo tee /var/www/html/index.html

#Now lets restart our Nginx so that it can know about our web page
echo "Restarting Nginx..."
sudo service nginx restart

#we are saying its all good now you can visit our web page to see Hello World
echo "Nginx has been installed and configured. You can jump in and see Hello World!"
