#!/usr/bin/env bash
#Configures a new ubuntu machine by installing
#Nginx where it should listening on port 80
#Serve a page that will return Hello World page

echo -e "Updating and Installing Nginx...\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y
echo -e "\nSetting up some small things..\n"

#Starting Nginx service
sudo service nginx start

#Allow nginx on firewall
sudo ufw allow 'Nginx HTTP'

#Give the user ownership to website to edit easly
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#Backing up index page
cp /var/www/html/index.ngenx-debain.html /var/www/html/index.ingenx-debian.html.bckp

#Creating a new index
echo -e "Hello World!" > /var/www/html/index.ingenx-debian.html

#Setting up /redirect_me to a youtube video
sudo bash -c 'echo "server {
    listen 80;
    listen [::]:80;
    root /var/www/html;
    index index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}" > /etc/nginx/sites-available/default'

#Restarting Nginx
sudo service nginx restart

echo -e "\nCompleted.\n"
