#!/usr/bin/env bash
# We configures a server to listening on port 80 of all servers active IPv4 IPs

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-anabled/default
sudo service nginx restart
